In [2]:
#%%
import os
import sys

PROJECT_NAME = 'sales-forecasting'

try:

    from google.colab import drive
    drive.mount('/content/drive')

    PROJECT_ROOT = f'/content/drive/My Drive/Data Science/Personal/{PROJECT_NAME}'

    print("Running in Google Colab.")

except:

    PROJECT_ROOT = rf'D:/Data-Science/Projects/Personal/{PROJECT_NAME}'

    print("Running in local environment.")

# Move to project root
os.chdir(PROJECT_ROOT)

print("Current working directory:", os.getcwd())

# Add project root to Python path
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

Running in local environment.
Current working directory: D:\Data-Science\Projects\Personal\sales-forecasting

In [4]:

from src.config.config import ProjectConfig
from src.data.data_loader import DataLoader

config = ProjectConfig(
    project_name="Sales Forecasting",
    raw_data_path="data/raw/sales.csv",
    processed_data_path = "data/processed/sales_clean.csv"
)

config.show_project_name()
config.show_data_paths()

Project Name: Sales Forecasting
Raw Data Path: data/raw/sales.csv
Processed Data Path: data/processed/sales_clean.csv

In [5]:
loader = DataLoader("data/raw/train.csv")
df = loader.load_data()
df
print(df.shape)
print(df.columns)

(1017209, 9)
Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='str')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  str
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(1), str(1)
memory usage: 69.8+ MB

In [20]:
df.sample(10)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
777493,9,6,2013-08-03,4893,447,1,0,0,0
416433,209,1,2014-06-23,5788,690,1,0,0,0
105984,60,1,2015-04-27,12002,905,1,1,0,0
935949,135,4,2013-03-14,4547,428,1,0,0,0
568079,215,5,2014-02-07,7656,530,1,1,0,0
321110,697,4,2014-10-02,14271,1338,1,1,0,0
738306,962,7,2013-09-08,0,0,0,0,0,0
545285,836,5,2014-02-28,5592,711,1,0,0,1
469827,83,2,2014-05-06,4352,371,1,1,0,0
353141,982,5,2014-08-29,8008,775,1,0,0,1

In [21]:
df.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00

In [22]:
df["Sales"].describe()

count    1.017209e+06
mean     5.773819e+03
std      3.849926e+03
min      0.000000e+00
25%      3.727000e+03
50%      5.744000e+03
75%      7.856000e+03
max      4.155100e+04
Name: Sales, dtype: float64

In [29]:
df["Store"].value_counts()

Store
1       942
2       942
3       942
4       942
5       942
       ...
1094    758
1102    758
1104    758
1107    758
1109    758
Name: count, Length: 1115, dtype: int64

In [30]:
df.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [31]:
df["Sales"].isnull().sum()

np.int64(0)

In [32]:
df["Sales"].mean()

np.float64(5773.818972305593)