In [1]:
#%%
import os
import sys

PROJECT_NAME = 'sales-forecasting'

try:

    from google.colab import drive
    drive.mount('/content/drive')

    PROJECT_ROOT = f'/content/drive/My Drive/Data Science/Personal/{PROJECT_NAME}'

    print("Running in Google Colab.")

except:

    PROJECT_ROOT = rf'D:/Data-Science/Projects/Personal/{PROJECT_NAME}'

    print("Running in local environment.")

# Move to project root
os.chdir(PROJECT_ROOT)

print("Current working directory:", os.getcwd())

# Add project root to Python path
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

Running in local environment.
Current working directory: D:\Data-Science\Projects\Personal\sales-forecasting

In [2]:

from src.config.config import ProjectConfig
from src.data.data_loader import DataLoader
from src.data.data_cleaner import DataCleaner

config = ProjectConfig(
    project_name="Sales Forecasting",
    raw_data_path="data/raw/sales.csv",
    processed_data_path = "data/processed/sales_clean.csv"
)

config.show_project_name()
config.show_data_paths()

loader = DataLoader("data/raw/train.csv")
df = loader.load_data()
df

Running in local environment.
Current working directory: D:\Data-Science\Projects\Personal\sales-forecasting
Running in local environment.
Current working directory: D:\Data-Science\Projects\Personal\sales-forecasting
3.0.3
Running in local environment.
Current working directory: D:\Data-Science\Projects\Personal\sales-forecasting
Project Name: Sales Forecasting
Raw Data Path: data/raw/sales.csv
Processed Data Path: data/processed/sales_clean.csv

D:\Data-Science\Projects\Personal\sales-forecasting\src\data\data_loader.py:46: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  self.dataFrame = pd.read_csv(self.file_path)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [3]:

print(df.shape)
print(df.columns)

(1017209, 9)
Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='str')

In [4]:
cleaner = DataCleaner(df)
cleaner.check_missing()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  str
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(1), str(1)
memory usage: 69.8+ MB

In [6]:
df.sample(10)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
366754,486,4,2014-08-14,3528,513,1,0,0,1
789436,802,3,2013-07-24,4894,408,1,0,0,1
684686,862,6,2013-10-26,5108,721,1,0,0,0
934345,761,6,2013-03-16,6696,760,1,0,0,0
682399,805,1,2013-10-28,4546,512,1,0,0,1
644875,76,6,2013-11-30,9814,962,1,0,0,0
874432,1058,4,2013-05-09,0,0,0,0,a,0
229968,279,2,2015-01-06,0,0,0,1,a,0
202070,256,6,2015-01-31,9051,1220,1,0,0,0
366598,310,4,2014-08-14,8594,722,1,0,0,1

In [7]:
df.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00

In [8]:
df["Sales"].describe()

count    1.017209e+06
mean     5.773819e+03
std      3.849926e+03
min      0.000000e+00
25%      3.727000e+03
50%      5.744000e+03
75%      7.856000e+03
max      4.155100e+04
Name: Sales, dtype: float64

In [9]:
df["Store"].value_counts()

Store
1       942
2       942
3       942
4       942
5       942
       ...
1094    758
1102    758
1104    758
1107    758
1109    758
Name: count, Length: 1115, dtype: int64

In [10]:
df.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [11]:
cleaner.check_missing()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [12]:
cleaner = DataCleaner(df)
cleaner.check_missing()

df_cleaned = cleaner.handle_missing(strategy="drop")
df_cleaned.shape

df_converted = cleaner.convert_types()

df_converted.dtypes

Store                     int64
DayOfWeek                 int64
Date             datetime64[us]
Sales                     int64
Customers                 int64
Open                      int64
Promo                     int64
StateHoliday           category
SchoolHoliday             int64
dtype: object

In [13]:
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  datetime64[us]
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  category
 8   SchoolHoliday  1017209 non-null  int64
dtypes: category(1), datetime64[us](1), int64(7)
memory usage: 63.1 MB

In [14]:
df_converted.shape

(1017209, 9)

In [15]:
df_unique= cleaner.remove_duplicates()
df_unique.shape

(1017209, 9)

In [16]:
df_normalized = cleaner.normalize_columns()
df_normalized.columns

Index(['store', 'dayofweek', 'date', 'sales', 'customers', 'open', 'promo',
       'stateholiday', 'schoolholiday'],
      dtype='str')

In [17]:
df_normalized["open"].value_counts()

open
1    844392
0    172817
Name: count, dtype: int64

In [19]:
df_filtered = cleaner.filter_rows(condition_column="open", condition_column_value=1)
df_filtered["open"].value_counts()

open
1    844392
Name: count, dtype: int64