In [31]:
#%%
import os
import sys

PROJECT_NAME = 'sales-forecasting'

try:

    from google.colab import drive
    drive.mount('/content/drive')

    PROJECT_ROOT = f'/content/drive/My Drive/Data Science/Personal/{PROJECT_NAME}'

    print("Running in Google Colab.")

except:

    PROJECT_ROOT = rf'D:/Data-Science/Projects/Personal/{PROJECT_NAME}'

    print("Running in local environment.")

# Move to project root
os.chdir(PROJECT_ROOT)

print("Current working directory:", os.getcwd())

# Add project root to Python path
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

Running in local environment.
Current working directory: D:\Data-Science\Projects\Personal\sales-forecasting

In [32]:
# Importing class
from src.config.config import ProjectConfig
from src.data.data_loader import DataLoader
from src.data.data_cleaner import DataCleaner
from src.features.features_engineer import FeatureEngineer

# Configuration
config = ProjectConfig(
    project_name="Sales Forecasting",
    raw_data_path="data/raw/sales.csv",
    processed_data_path = "data/processed/sales_clean.csv"
)

config.show_project_name()
config.show_data_paths()

# Data Loader
loader = DataLoader("data/raw/train.csv")
df = loader.load_data()
df

Project Name: Sales Forecasting
Raw Data Path: data/raw/sales.csv
Processed Data Path: data/processed/sales_clean.csv

D:\Data-Science\Projects\Personal\sales-forecasting\src\data\data_loader.py:46: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  self.dataFrame = pd.read_csv(self.file_path)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [ ]:

print(df.shape)
print(df.columns)

In [ ]:
cleaner = DataCleaner(df)
cleaner.check_missing()

In [ ]:
df.info()

In [ ]:
df.sample(10)

In [ ]:
df.describe()

In [ ]:
df["Sales"].describe()

In [ ]:
df["Store"].value_counts()

In [ ]:
df.isnull().sum()

In [ ]:
cleaner.check_missing()

In [ ]:
cleaner = DataCleaner(df)
cleaner.check_missing()

df_cleaned = cleaner.handle_missing(strategy="drop")
df_cleaned.shape

df_converted = cleaner.convert_types()

df_converted.dtypes

In [ ]:
df_cleaned.info()

In [ ]:
df_converted.shape

In [ ]:
df_unique= cleaner.remove_duplicates()
df_unique.shape

In [ ]:
df_normalized = cleaner.normalize_columns()
df_normalized.columns

In [ ]:
df_normalized["open"].value_counts()

In [ ]:
df_filtered = cleaner.filter_rows(condition_column="open", condition_column_value=1)
df_filtered["open"].value_counts()

In [33]:
cleaner = DataCleaner(df)
cleaner.check_missing()

df_cleaned = cleaner.handle_missing(strategy="drop")
df_cleaned.shape

df_converted = cleaner.convert_types()
df_converted.dtypes

df_unique= cleaner.remove_duplicates()
df_unique.shape

df_normalized = cleaner.normalize_columns()
df_normalized.columns

df_filtered = cleaner.filter_rows(condition_column="open", condition_column_value=1)
df_filtered["open"].value_counts()

df_filtered.info()

<class 'pandas.DataFrame'>
Index: 844392 entries, 0 to 1017190
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   store          844392 non-null  int64
 1   dayofweek      844392 non-null  int64
 2   date           844392 non-null  datetime64[us]
 3   sales          844392 non-null  int64
 4   customers      844392 non-null  int64
 5   open           844392 non-null  int64
 6   promo          844392 non-null  int64
 7   stateholiday   844392 non-null  category
 8   schoolholiday  844392 non-null  int64
dtypes: category(1), datetime64[us](1), int64(7)
memory usage: 58.8 MB

In [34]:
engineer = FeatureEngineer(df_filtered)
df_feature = engineer.add_date_part()

df_feature

,store,dayofweek,date,sales,customers,open,promo,stateholiday,schoolholiday,year,month,day
0,1,5,2015-07-31,5263,555,1,1,0,1,2015,7,31
1,2,5,2015-07-31,6064,625,1,1,0,1,2015,7,31
2,3,5,2015-07-31,8314,821,1,1,0,1,2015,7,31
3,4,5,2015-07-31,13995,1498,1,1,0,1,2015,7,31
4,5,5,2015-07-31,4822,559,1,1,0,1,2015,7,31
...,...,...,...,...,...,...,...,...,...,...,...,...
1016776,682,2,2013-01-01,3375,566,1,0,a,1,2013,1,1
1016827,733,2,2013-01-01,10765,2377,1,0,a,1,2013,1,1
1016863,769,2,2013-01-01,5035,1248,1,0,a,1,2013,1,1
1017042,948,2,2013-01-01,4491,1039,1,0,a,1,2013,1,1
1017190,1097,2,2013-01-01,5961,1405,1,0,a,1,2013,1,1